sudo: false
matrix:
  allow_failures:
    - env: ALLOW_ME_TO=FAIL
  include:
    ####################################################################################
    # Linux :: Python :: 2.7                                                           #
    ####################################################################################
    - os: linux
      addons:
        apt:
          packages:
            - doxygen
      language: python
      python: "2.7"
      install:
        - pip install -U tox codecov
      script:
        - doxygen --version
        - tox -e py -- --cov=exhale
      after_success:
        - codecov --name linux_py2.7
    ####################################################################################
    # Linux :: Python :: 3.6                                                           #
    ####################################################################################
    - os: linux
      addons:
        apt:
          packages:
            - doxygen
      language: python
      python: "3.6"
      install:
        - pip install -U tox codecov
      script:
        - doxygen --version
        - tox -e py -- --cov=exhale
      after_success:
        - codecov --name linux_py3.6
    ####################################################################################
    # OSX :: Python :: 2.7                                                             #
    ####################################################################################
    - os: osx
      language: generic
      env: PYTHON=2.7
      before_install:
        # Something strange about final step of install gives exit code != 1 but the
        # installation appears to work?
        - brew install python@2 || true
      install:
        - brew install doxygen
        - /usr/local/bin/pip install -U tox codecov
      script:
        - doxygen --version
        - /usr/local/bin/python2 --version
        - /usr/local/bin/python2 -m tox -e py -- --cov=exhale
      after_success:
        - codecov --name osx_py2.7
    ####################################################################################
    # OSX :: Python :: 3.6                                                             #
    ####################################################################################
    - os: osx
      language: generic
      env: PYTHON=3.6
      before_install:
        - brew upgrade python
      install:
        - brew install doxygen
        - /usr/local/bin/pip3 install -U tox codecov
      script:
        - doxygen --version
        - /usr/local/bin/python3 --version
        - /usr/local/bin/python3 -m tox -e py -- --cov=exhale
      after_success:
        - codecov --name osx_py3.6
    ####################################################################################
    # Flake8                                                                           #
    ####################################################################################
    - os: linux
      language: python
      env: TEST=flake8
      python: "3.6"
      install:
        - pip install -U tox
      script:
        - tox -e flake8
    ####################################################################################
    # Docs and Linkcheck                                                               #
    ####################################################################################
    - os: linux
      addons:
        apt:
          packages:
            - graphviz
      language: python
      python: "3.6"
      env: TEST=docs_linkcheck
      install:
        - pip install -U tox
      script:
        - tox -e docs,linkcheck
