sudo: false

branches:
  except:
    # Ignore fix/* branches since they'll also have a Pull Request build
    - /^fix.*$/
    # Ignore feature/* branches since they'll also have a Pull Request build
    - /^feature.*$/

linux_apt: &linux_apt
  apt:
    packages:
      # The dependencies for compiling doxygen from source.
      - flex
      - bison

linux_install_script: &linux_install
  - curl -LO http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.14.src.tar.gz
  - tar -xf doxygen-1.8.14.src.tar.gz
  - cd doxygen-1.8.14/
  - mkdir build && cd build/
  - cmake ..
  - make -j
  - export PATH="$PWD/bin:$PATH"
  # Go back to repository root for the rest
  - cd $(git rev-parse --show-toplevel)
  - pip install -U pip setuptools tox codecov

matrix:
  allow_failures:
    - env: ALLOW_ME_TO=FAIL
  include:
    ####################################################################################
    # Linux :: Python :: 2.7                                                           #
    ####################################################################################
    - os: linux
      addons: *linux_apt
      language: python
      python: "2.7"
      install: *linux_install
      script:
        - doxygen --version
        - tox -e py -- --cov=exhale --cov=testing
      after_success:
        - codecov --name linux_py2.7
    ####################################################################################
    # Linux :: Python :: 3.6                                                           #
    ####################################################################################
    - os: linux
      addons: *linux_apt
      language: python
      python: "3.6"
      install: *linux_install
      script:
        - doxygen --version
        - tox -e py -- --cov=exhale --cov=testing
      after_success:
        - codecov --name linux_py3.6
    ####################################################################################
    # OSX :: Python :: 2.7                                                             #
    ####################################################################################
    - os: osx
      language: generic
      env: PYTHON=2.7
      before_install:
        # Something strange about final step of install gives exit code != 1 but the
        # installation appears to work?
        - brew install python@2 || true
      install:
        - brew install doxygen
        - /usr/local/bin/pip install -U tox codecov
      script:
        - doxygen --version
        - /usr/local/bin/python2 --version
        - /usr/local/bin/python2 -m tox -e py -- --cov=exhale --cov=testing
      after_success:
        - codecov --name osx_py2.7
    ####################################################################################
    # OSX :: Python :: 3.6                                                             #
    ####################################################################################
    - os: osx
      language: generic
      env: PYTHON=3.6
      before_install:
        - brew upgrade python
      install:
        - brew install doxygen
        - /usr/local/bin/pip3 install -U tox codecov
      script:
        - doxygen --version
        - /usr/local/bin/python3 --version
        - /usr/local/bin/python3 -m tox -e py -- --cov=exhale --cov=testing
      after_success:
        - codecov --name osx_py3.6
    ####################################################################################
    # Flake8                                                                           #
    ####################################################################################
    - os: linux
      language: python
      env: TEST=flake8
      python: "3.6"
      install:
        - pip install -U tox
      script:
        - tox -e flake8
    ####################################################################################
    # Docs and Linkcheck                                                               #
    ####################################################################################
    - os: linux
      addons:
        apt:
          packages:
            - graphviz
      language: python
      python: "3.6"
      env: TEST=docs_linkcheck
      install:
        - pip install -U tox
      script:
        - tox -e docs,linkcheck
    ####################################################################################
    # testing/projects Code Validation                                                 #
    ####################################################################################
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - gfortran-7
            - cmake
      language: cpp  # mostly ;)
      env: TEST=testing/projects
      before_install:
        - export CC=gcc-7
        - export CXX=g++-7
        - export FC=gfortran-7
      install:
        # I don't want to require sudo because I don't want to wait ;)
        - pip install virtualenv
        - virtualenv venv
        - source venv/bin/activate
        - pip install -U pip codecov gcovr
        # cpp_long_names test runs code from testing/tests/cpp_long_names.py, so we need
        # to install the runtime dependencies of Exhale's Python tests.
        - pip install -r requirements.txt -r requirements-dev.txt
      script:
        - cd testing/projects
        - mkdir build && cd build
        - cmake --version
        - cmake ..
        - make -j
        - make coverage-xml
      after_success:
        - codecov --name linux_cxx

