name: Test Extras
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_docs:
    name: Docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Use Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Tools
        run: |
          pip install -U tox
          sudo apt-get install -y graphviz
      - name: Test Docs
        run: |
          tox -e docs

  build_linkcheck:
    name: Linkcheck
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Use Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Tools
        run: |
          pip install -U tox
      - name: Test Linkcheck
        run: |
          tox -e linkcheck

  build_flake8:
    name: Flake8
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Use Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Tools
        run: |
          pip install -U tox
      - name: Test Flake8
        run: |
          tox -e flake8

  build_dist:
    name: Packaging
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      # Use minimum version of python needed for this project in setup.cfg.
      - name: Use Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install Tools
        run: |
          pip install -U tox
      - name: Test Packaging
        run: |
          tox -e dist
